"""Adding category and population groups.

Revision ID: 157debc89661
Revises: 51589067470d
Create Date: 2015-08-25 22:19:38.050000

"""

# revision identifiers, used by Alembic.
revision = '157debc89661'
down_revision = '51589067470d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('order', sa.Float(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('population_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('order', sa.Float(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'category', sa.Column('grouping_id', sa.Integer(), nullable=True))
    op.add_column(u'population', sa.Column('grouping_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'population', 'grouping_id')
    op.drop_column(u'category', 'grouping_id')
    op.drop_table('population_group')
    op.drop_table('category_group')
    ### end Alembic commands ###
