"""Adding LoginHistory table

Revision ID: 15ba1cfb5eef
Revises: 585fd56a9833
Create Date: 2015-05-31 19:52:02.437000

"""

# revision identifiers, used by Alembic.
revision = '15ba1cfb5eef'
down_revision = '585fd56a9833'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_date', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.Unicode(length=45), nullable=False),
    sa.Column('username', sa.Unicode(length=50), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Unicode(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history')
    ### end Alembic commands ###
