"""Adding resource.notes column

Revision ID: 17929a019cff
Revises: 458806f777d8
Create Date: 2015-04-26 22:21:32.009000

"""

# revision identifiers, used by Alembic.
revision = '17929a019cff'
down_revision = '458806f777d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('notes', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'notes')
    ### end Alembic commands ###
