"""Adding user columns for email confirmation, password resets, and a display name.

Revision ID: 1fa61500b159
Revises: cecb3808cb0
Create Date: 2014-11-09 17:07:00.503000

"""

# revision identifiers, used by Alembic.
revision = '1fa61500b159'
down_revision = 'cecb3808cb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.Unicode(length=100), server_default='', nullable=False))
    op.add_column('user', sa.Column('email_activated', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('user', sa.Column('email_code', sa.Unicode(length=36), nullable=True))
    op.add_column('user', sa.Column('reset_pass_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_pass_date')
    op.drop_column('user', 'email_code')
    op.drop_column('user', 'email_activated')
    op.drop_column('user', 'display_name')
    ### end Alembic commands ###
