"""empty message

Revision ID: 21755fb07ccb
Revises: 138528274c6d
Create Date: 2014-11-05 15:21:18.914948

"""

# revision identifiers, used by Alembic.
revision = '21755fb07ccb'
down_revision = '138528274c6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
