"""Adding relationship for getting top-level resource aggregate scores.

Revision ID: 26aa7051f714
Revises: 26d585c909b0
Create Date: 2016-08-14 02:14:35.694000

"""



# revision identifiers, used by Alembic.
revision = '26aa7051f714'
down_revision = '26d585c909b0'

from alembic import op

import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
