"""Adding an advisory notes column for resources.

Revision ID: 26d585c909b0
Revises: 1726eb3f34a5
Create Date: 2016-04-18 23:30:33.980000

"""

# revision identifiers, used by Alembic.
revision = '26d585c909b0'
down_revision = '1726eb3f34a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('advisory_notes', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'advisory_notes')
    ### end Alembic commands ###
