"""Adding resource hours and NPI columns.

Revision ID: 2c5bd010030f
Revises: 1fa61500b159
Create Date: 2014-12-06 00:12:54.238000

"""

# revision identifiers, used by Alembic.
revision = '2c5bd010030f'
down_revision = '1fa61500b159'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('hours', sa.UnicodeText(), nullable=True))
    op.add_column('resource', sa.Column('npi', sa.Unicode(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'npi')
    op.drop_column('resource', 'hours')
    ### end Alembic commands ###
