"""empty message

Revision ID: 2eaff8ea222
Revises: 4fe10b0a244c
Create Date: 2014-07-17 20:46:32.292623

"""

# revision identifiers, used by Alembic.
revision = '2eaff8ea222'
down_revision = '4fe10b0a244c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('fulladdress', sa.UnicodeText(), nullable=True))
    op.add_column('resource', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('resource', sa.Column('longitude', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'longitude')
    op.drop_column('resource', 'latitude')
    op.drop_column('resource', 'fulladdress')
    ### end Alembic commands ###
