"""Adding resource flags and hospital affiliation.

Revision ID: 3548e1ad8a3c
Revises: 157debc89661
Create Date: 2015-09-01 00:43:10.831000

"""

# revision identifiers, used by Alembic.
revision = '3548e1ad8a3c'
down_revision = '157debc89661'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('has_sliding_scale', sa.Boolean(), nullable=True))
    op.add_column('resource', sa.Column('hospital_affiliation', sa.UnicodeText(), nullable=True))
    op.add_column('resource', sa.Column('is_accessible', sa.Boolean(), nullable=True))
    op.add_column('resource', sa.Column('is_icath', sa.Boolean(), nullable=True))
    op.add_column('resource', sa.Column('is_wpath', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_wpath')
    op.drop_column('resource', 'is_icath')
    op.drop_column('resource', 'is_accessible')
    op.drop_column('resource', 'hospital_affiliation')
    op.drop_column('resource', 'has_sliding_scale')
    ### end Alembic commands ###
