"""Adding a field to track category keywords

Revision ID: 391a19c44a98
Revises: 2c5bd010030f
Create Date: 2015-04-04 23:32:06.075000

"""

# revision identifiers, used by Alembic.
revision = '391a19c44a98'
down_revision = '2c5bd010030f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('keywords', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'keywords')
    ### end Alembic commands ###
