"""Adding resource submission fields.

Revision ID: 3ec157e32f35
Revises: b511e51f3a0
Create Date: 2015-07-30 22:24:47.518000

"""

# revision identifiers, used by Alembic.
revision = '3ec157e32f35'
down_revision = 'b511e51f3a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_approved', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('resource', sa.Column('submitted_date', sa.DateTime(), nullable=True))
    op.add_column('resource', sa.Column('submitted_ip', sa.Unicode(length=45), nullable=True))
    op.add_column('resource', sa.Column('submitted_user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'submitted_user_id')
    op.drop_column('resource', 'submitted_ip')
    op.drop_column('resource', 'submitted_date')
    op.drop_column('resource', 'is_approved')
    ### end Alembic commands ###
