"""Adding a resource location field

Revision ID: 458806f777d8
Revises: 391a19c44a98
Create Date: 2015-04-07 00:06:11.513000

"""

# revision identifiers, used by Alembic.
revision = '458806f777d8'
down_revision = '391a19c44a98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('location', sa.Unicode(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'location')
    ### end Alembic commands ###
