"""Adding Resource model.

Revision ID: 4a09ad931d71
Revises: 3ec157e32f35
Create Date: 2015-07-30 22:33:07.145000

"""

# revision identifiers, used by Alembic.
revision = '4a09ad931d71'
down_revision = '3ec157e32f35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('keywords', sa.UnicodeText(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population')
    ### end Alembic commands ###
