"""empty message

Revision ID: 4fe10b0a244c
Revises: 2bd3dc6b61e4
Create Date: 2014-07-07 21:25:48.883309

"""

# revision identifiers, used by Alembic.
revision = '4fe10b0a244c'
down_revision = '2bd3dc6b61e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('visable', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'visable')
    ### end Alembic commands ###
