"""Adding model for aggregate review scores.



Revision ID: 51589067470d

Revises: 5736a0d64e8b

Create Date: 2015-08-06 22:53:47.325000



"""



# revision identifiers, used by Alembic.

revision = '51589067470d'

down_revision = '5736a0d64e8b'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_review_score',
    sa.Column('resource_id', sa.Integer(), nullable=False, autoincrement=False),
    sa.Column('population_id', sa.Integer(), nullable=False, autoincrement=False),
    sa.Column('num_ratings', sa.Integer(), nullable=False),
    sa.Column('first_reviewed', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('staff_rating_avg', sa.Float(), nullable=True),
    sa.Column('intake_rating_avg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'population_id')
    )
    ### end Alembic commands ###





def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_review_score')
    ### end Alembic commands ###

