"""Adding Resource.date_verified column.

Revision ID: 585fd56a9833
Revises: 112a6dc89516
Create Date: 2015-05-27 21:56:05.917000

"""

# revision identifiers, used by Alembic.
revision = '585fd56a9833'
down_revision = '112a6dc89516'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('date_verified', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'date_verified')
    ### end Alembic commands ###
