"""Nulling submitted user ID on delete.

Revision ID: 58620e8a20f9
Revises: 3548e1ad8a3c
Create Date: 2015-09-19 22:13:49.310000

"""

# revision identifiers, used by Alembic.
revision = '58620e8a20f9'
down_revision = '3548e1ad8a3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
