"""Adding user password column

Revision ID: 59d49cf2f06a
Revises: 5a641be2bc51
Create Date: 2014-08-21 00:16:37.482000

"""

# revision identifiers, used by Alembic.
revision = '59d49cf2f06a'
down_revision = '5a641be2bc51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.Unicode(length=128), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
