"""empty message

Revision ID: 5a641be2bc51
Revises: 40cabbd5d298
Create Date: 2014-07-26 19:23:38.626103

"""

# revision identifiers, used by Alembic.
revision = '5a641be2bc51'
down_revision = '40cabbd5d298'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('date_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'date_created')
    ### end Alembic commands ###
