"""empty message

Revision ID: 6a5adbaaf49
Revises: 4fe10b0a244c
Create Date: 2014-07-12 20:32:56.679883

"""

# revision identifiers, used by Alembic.
revision = '6a5adbaaf49'
down_revision = '4fe10b0a244c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.UnicodeText(), nullable=False),
    sa.Column('email', sa.UnicodeText(), nullable=False),
    sa.Column('gender_identity', sa.UnicodeText(), nullable=True),
    sa.Column('pronouns', sa.UnicodeText(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('race', sa.Unicode(length=20), nullable=True),
    sa.Column('sexual_orientation', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
