"""Adds support for superseding old reviews with new reviews

Revision ID: cecb3808cb0
Revises: 138528274c6d
Create Date: 2014-10-31 00:24:40.305000

"""

# revision identifiers, used by Alembic.
revision = 'cecb3808cb0'
down_revision = '138528274c6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('is_old_review', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('review', sa.Column('new_review_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'new_review_id')
    op.drop_column('review', 'is_old_review')
    ### end Alembic commands ###
