"""empty message

Revision ID: 22f577241af8
Revises: None
Create Date: 2014-06-05 01:47:03.689423

"""

# revision identifiers, used by Alembic.
revision = '22f577241af8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('street', sa.UnicodeText(), nullable=True),
    sa.Column('city', sa.UnicodeText(), nullable=True),
    sa.Column('state', sa.UnicodeText(), nullable=True),
    sa.Column('country', sa.UnicodeText(), nullable=True),
    sa.Column('zipcode', sa.UnicodeText(), nullable=True),
    sa.Column('email', sa.UnicodeText(), nullable=True),
    sa.Column('phone', sa.UnicodeText(), nullable=True),
    sa.Column('fax', sa.UnicodeText(), nullable=True),
    sa.Column('url', sa.UnicodeText(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('source', sa.UnicodeText(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource')
    op.drop_table('category')
    ### end Alembic commands ###
